import {Red_Hat_Display} from "next/font/google";
import "./globals.css";

const redHatDisplay = Red_Hat_Display({subsets: ["latin"]});

export const metadata = {
    title: "Aplikasi Belanita",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={redHatDisplay.className}>
        {children}
        </body>
        </html>
    );
}
